repos:
  # Ruff as your primary linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.3
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  # Static typing
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
      - id: mypy
        args: [ "--strict" ]
        additional_dependencies:
          - fastmcp>=2.0.0
          - aiohttp>=3.12.12
          - requests>=2.32.4
          - types-requests
          - pytest>=8.4.1
          - pytest-asyncio>=1.0.0
          - aioresponses>=0.7.6

  # Upgrade Python syntax
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.9.0
    hooks:
      - id: pyupgrade
        args: [ "--py310-plus" ]

  # Check for large files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: [ "--maxkb=5000" ]

      - id: check-json
